# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          KROSS
paginate:       5
#baseurl:        "/tale"
baseurl:        "/blog.kross03"
url:            "https://movablecode.github.io/blog.kross03"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         KROSS
  url:          http://90days.kr/
  email:        27@kross.kr

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/movablecode/blog.kross03

# Gems
plugins:
  - jekyll-paginate

